FROM golang:1.24-alpine3.20 AS builder
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
RUN apk add --no-cache make
RUN apk add --no-cache bash
RUN apk add --no-cache git
RUN which bash
WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN make ci

FROM alpine:3.21.3
COPY --from=builder /usr/src/app/bin/pushprox-client /usr/bin
CMD ["pushprox-client"]