FROM golang:1.22-alpine3.18 as builder
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
RUN apk add --no-cache make
RUN apk add --no-cache bash
RUN apk add --no-cache git
RUN which bash
WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN make ci

FROM alpine:3.19.1
COPY --from=builder /usr/src/app/bin/pushprox-client /usr/bin
CMD ["pushprox-client"]