#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../


mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi
LINKFLAGS="-X github.com/rancher/pushprox.Version=$VERSION"
LINKFLAGS="-X github.com/rancher/pushprox.GitCommit=$COMMIT $LINKFLAGS"

for COMPONENT in proxy client
do
    pushd ./cmd/$COMPONENT
    CGO_ENABLED=0 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o ../../bin/pushprox-${COMPONENT}
    if [ "$CROSS" = "true" ] && [ "$ARCH" = "amd64" ]; then
        GOOS=darwin go build -ldflags "$LINKFLAGS" -o ../../bin/pushprox-${COMPONENT}-darwin
        GOOS=windows go build -ldflags "$LINKFLAGS" -o ../../bin/pushprox-${COMPONENT}-windows
    fi
    popd
done
