#!/bin/bash
set -e

function edit-chart() {
    perl -i -pe '
    s/^version:.*/version: '"${1}"'/;
    s/^appVersion:.*/appVersion: '\"${2}\"'/
' build/chart/Chart.yaml

    perl -i -pe 's/%TAG%/'"${2}"'/' build/chart/values.yaml
}

function package-chart() {
    helm package --debug -d ./dist/artifacts ./build/chart
}

if ! hash helm 2>/dev/null; then
    echo "Helm is not installed"
    exit 1
fi

cd $(dirname $0)/..
source ./scripts/version


rm -rf build/chart
mkdir -p build dist/artifacts
cp -rf chart build/

edit-chart ${HELM_CHART_VERSION} ${HELM_IMAGE_TAG}

if ! package-chart; then
    echo "Packaging rancher-pushprox chart failed!"
fi
