#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

for COMPONENT in proxy client
do
    pushd ./cmd/${COMPONENT}
    
    PACKAGES="$(go list ./...)"

    if ! command -v golangci-lint; then
        echo "Skipping validation for ${COMPONENT}: no golangci-lint available"
        exit
    fi

    echo "Running validation for ${COMPONENT}"

    echo "Running: golangci-lint for ${COMPONENT}"
    golangci-lint run

    echo "Running: go fmt for ${COMPONENT}:"

    test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"

    popd
done