#!/bin/bash
set -e

cd $(dirname $0)/..

for COMPONENT in proxy client
do
    pushd ./cmd/${COMPONENT}
    go generate
    popd
done

source ./scripts/version

if [ -n "$DIRTY" ]; then
    echo Git is dirty
    git status
    git diff
    exit 1
fi
