#!/bin/bash

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

SUFFIX="-${ARCH}"

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

HELM_IMAGE_TAG=${HELM_IMAGE_TAG:-${VERSION}}
if [ "$VERSION" == "$COMMIT" ]; then
  HELM_CHART_VERSION="0.0.0-dev.${COMMIT}"
else
  HELM_CHART_VERSION=${HELM_IMAGE_TAG/v/}
fi

echo $HELM_IMAGE_TAG
echo $HELM_CHART_VERSION

if echo $TAG | grep -q dirty; then
    TAG=dev
fi
